apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anu-app
  template:
    metadata:
      labels:
        app: anu-app
    spec:
      containers:
      - name: travel
        image: anusha552/travel:v1
        ports:
        - containerPort: 4000
        env:
            - name: MONGO_URI
              value: mongodb://mongo-svc:27017/sujitha
